import Head from 'next/head'
import Layout from '@layout/Layout'
import {useSelector , useDispatch} from 'react-redux'
import { increment , decrement, counterValue } from '@slices/counter'

export default function Home() {

  const count = useSelector(counterValue)
  const dispatch = useDispatch()
  return (
    <>
      <Head>
        <title>Musica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <>
          <h2 className='text-3xl font-iranyekan-bold p-8'>عدد {count}</h2>
          <button className='px-4 py-2 bg-green-400' onClick={() => dispatch(increment())}>Increment +1</button>
          <button className='px-4 py-2 bg-red-400' onClick={() => dispatch(decrement())}>Decrement -1</button>
        </>
      </Layout>      
    </>
  )
}
