import Head from 'next/head'
import Layout from '@layout/Layout'

export default function Home() {


  return (
    <>
      <Head>
        <title>Musica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <>
          <h2 className='text-3xl font-iranyekan-'>سینما تیکت</h2>
          <h2 className='text-3xl font-iranyekan-light'>سینما تیکت</h2>
          <h2 className='text-3xl font-iranyekan-regular'>سینما تیکت</h2>
          <h2 className='text-3xl font-iranyekan-medium'>سینما تیکت</h2>
          <h2 className='text-3xl font-iranyekan-bold'>سینما تیکت</h2>
          <h2 className='text-3xl font-iranyekan-extraBold'>سینما تیکت</h2>
          <h2 className='text-3xl font-iranyekan-black'>سینما تیکت</h2>
          <h2 className='text-3xl font-iranyekan-extraBlack'>سینما تیکت</h2>
        </>
      </Layout>      
    </>
  )
}
